apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cipher-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cipher-server
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
