apiVersion: v1
kind: Service
metadata:
  name: cipher-server-service
spec:
  type: NodePort
  selector:
    app: cipher-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
